// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qIA0jN-b0wCBn2Y0aDjCLlj-W8tVx6w',
    appId: '1:841144199743:android:0249a72f3874d8eed2268a',
    messagingSenderId: '841144199743',
    projectId: 'myfirstapp-1eea4',
    storageBucket: 'myfirstapp-1eea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO5tc0jz_EdLyUtuBRbcf2Rj_k3hWu7PE',
    appId: '1:841144199743:ios:b57c92f8c1a99eeed2268a',
    messagingSenderId: '841144199743',
    projectId: 'myfirstapp-1eea4',
    storageBucket: 'myfirstapp-1eea4.appspot.com',
    androidClientId: '841144199743-lsqig52q0b9ao5n83vuap43m0847d0vv.apps.googleusercontent.com',
    iosClientId: '841144199743-snbi3u3qieegq2skaohntpla2deagbe8.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.myfirstapp',
  );
}
